import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
const APP='https://app.neto.pe';
const PLAN=(process.argv[2]||'pro').toLowerCase();
const P=PLAN==='free'?'NETO_QA_FREE_':'NETO_QA_';
function le(p){const e={};for(const l of readFileSync(p,'utf8').split(/\r?\n/)){const m=l.match(/^([A-Z0-9_]+)=(.*)$/);if(m)e[m[1]]=m[2];}return e;}
const env=le(join(homedir(),'.config','neto','qa.env'));
const SUPA=env[P+'URL']||env.NETO_QA_URL,ANON=env[P+'ANON']||env.NETO_QA_ANON,EMAIL=env[P+'EMAIL'],PASSWORD=env[P+'PASSWORD']||env.NETO_QA_PASSWORD;
const ref=new URL(SUPA).hostname.split('.')[0],cn=`sb-${ref}-auth-token`;
const g=await fetch(`${SUPA}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:ANON,'Content-Type':'application/json'},body:JSON.stringify({email:EMAIL,password:PASSWORD})});
const s=await g.json();
const v='base64-'+Buffer.from(JSON.stringify(s),'utf8').toString('base64url');
const MAX=3180,domain=new URL(APP).hostname,ck=[];
if(v.length<=MAX)ck.push({name:cn,value:v});else for(let i=0,p=0;p<v.length;i++,p+=MAX)ck.push({name:`${cn}.${i}`,value:v.slice(p,p+MAX)});
const br=await chromium.launch();const ctx=await br.newContext({viewport:{width:1280,height:1400}});
await ctx.addCookies(ck.map(c=>({name:c.name,value:c.value,domain,path:'/',httpOnly:false,secure:true,sameSite:'Lax'})));
await ctx.addInitScript(()=>{try{localStorage.setItem('neto_tour_v2','true');localStorage.setItem('neto_welcome_seen','1');}catch{}});
const pg=await ctx.newPage();
await pg.goto(`${APP}/dashboard`,{waitUntil:'domcontentloaded'});
await pg.getByText(/S\/\s*[\d.,]+/).first().waitFor({timeout:20000}).catch(()=>{});
await pg.waitForTimeout(3500);
const R={plan:PLAN};
R.calendarGateVisible=await pg.getByText('Calendario financiero').first().isVisible().catch(()=>false);
R.calendarGridVisible=await pg.getByText(/Vencimiento deuda/).first().isVisible().catch(()=>false);
R.csvCrown=await pg.getByText('CSV').first().isVisible().catch(()=>false);
console.log(JSON.stringify(R));
await br.close();
